### ISSUE TITLE
Width on Mobile Not adjusting correctly

### ISSUE THREAD

**Issue by louiswilbrink** [scottcorgan/angular-gist#3]
Hi Scott,

  When I view a gist on mobile, the width doesn't shrink down to its parent.  I see there you are using Github-Gist's embedded css, and I haven't been able to override the width: 100%.  Has anyone else been seeing this, or do you know if this is a reality using gists?

Best,

Louis W

**Comment by scottcorgan** [comment]
What does your code look like to get the Gist to adjust to 100%?

**Comment by louiswilbrink** [comment]
HTML:
```html
<html ng-app="myApp">
<head>
  <meta name="viewport" content="width=device-width">
</head>
<body>
  <gist id="c298ba8be930ae658f53"></gist>
  <script src="bower_components/angular/angular.js"></script>
  <script src="bower_components/angular-gist/angular-gist.js"></script>
  <script src="index.js"></script>
</body>
</html>
```

JS:
```javascript
angular.module('myApp', ['gist']);
```

If I load this on my desktop browser, the width of my gist fits its parent correctly.  If i load this on iOS Simulator or iPhone, the gist will expand outside of its parent.

**Comment by louiswilbrink** [comment]
Hey Scott,

  I'm still not sure what the issue is with iOS browser, but i found a work around to size gists correctly on mobile.

  In the iframe html, I added a few extra style tags that would set the width for the .gist class at certain device widths.  I've forked your repo here: https://github.com/louiswilbrink/angular-gist

  I'm not sure if this is the solution you'd want to pull into you repo, but let me know your thoughts.

**Comment by scottcorgan** [comment]
Looks like a good solution. Go ahead and open a pull request with your fork.

**Comment by louiswilbrink** [comment]
Made the pull request.  Once it makes it into a release, I'll set my bower package to reference this repo again.  Thanks for making it, it's been great to use.

**Comment by scottcorgan** [comment]
Merged
