### ISSUE TITLE
Unable to use gist on angular strap modal 

### ISSUE THREAD

**Issue by sarfarazansari** [scottcorgan/angular-gist#7]
Hey,
am trying to use gist in a modal box. But it shows error while opening
Please take a look of attached image

![image](https://cloud.githubusercontent.com/assets/3416989/17134487/3ab69ce4-5348-11e6-8b91-786b93fee44d.png)

While debugging I found that issue is related to timeout. 
if somehow we load gist directive after modal opened then it will work fine.

It would be great if you can introduced timeout functionality in gist.

**Comment by scottcorgan** [comment]
I'm not in a position to fix the bug at this very moment. But, I'm very open of contributions and a pull request.

Thanks!

**Comment by sarfarazansari** [comment]
Fixed [commit](https://github.com/scottcorgan/angular-gist/commit/be0fc6f74918b324c28e818294b051b6f97362b3)
